### PR TITLE
Small overhauls

### PR DESCRIPTION
**Pull request by stevefan1999-personal**

### CODE REVIEW

**Comment by Paranoid-AF** [comment]
Sorry for the delay <3
Making use of opConv is very smart, and thank you for reconstructing JsonaMain class, as it shouldn't be a class in the first place.
I thought this repo won't be seen by anyone else on earth, so those comments are kinda funny.
Wiki is going to be modified soon™.

**Comment by Paranoid-AF** [comment]
By the way, I'm going to undo "set as new dict if key not exist", since I think data should not be modified by accessing get method. What's your opinion about that?

**Comment by stevefan1999-personal** [comment]
> 
> 
> By the way, I'm going to undo "set as new dict if key not exist", since I think data should not be modified by accessing get method. What's your opinion about that?

its ok, but i had real life use case of serializing a json structure as logger directly as one expression without declaring the dicts first, so this I think is pretty handy:
```
	if (CMetaData::Log::Level <= LogLevel::TRACE) {
		g_Log.PrintF("%1\n", Jsona::Value(dictionary = {
			{"type", Jsona::Value("TRACE")}, {"function", Jsona::Value("PluginInit")}
		}).stringify());
	}
```
So this won't work after you reverted it

**Comment by Paranoid-AF** [comment]
@stevefan1999-personal That code still work and prints `{"function":"PluginInit","type":"TRACE"}`. I was only changing `get_opIndex()` part in Jsona::Value. ;D

**Comment by stevefan1999-personal** [comment]
@Paranoid-AF what about something more complicated🤔
```js
		if (CMetaData::Log::Level <= LogLevel::TRACE) {
			g_Log.PrintF("%1\n", Jsona::Value(dictionary = {
				{"type", Jsona::Value("TRACE")}, {"message", Jsona::Value("traversal")}, {"args", Jsona::Value(dictionary = {{"weapon", Jsona::Value(wpnClassname)}})}
			}).stringify());
		}
```

**Comment by Paranoid-AF** [comment]
@stevefan1999-personal 
Yes, and it prints out like this: `{"args":{"weapon":"wpnClassname"},"message":"traversal","type":"TRACE"}` (I was assuming wpnClassname was a string.)

The only thing changed is `[ ]`'s operator overload. aka opIndex. I didn't make this clear, sorry. XD

**Pull request merged**
